print('Здавствуй')
print('Как тебя зовут?')
my_name = input()
print('Рад с тобой познакомится, ' + my_name)
print('Длина твоего имени:')
print(len(my_name), ' буквы')
print('Сколько тебе лет?')
my_age = input()
print('Через год тебе будет ' + str(int(my_age) + 1) + ' лет')